### ISSUE TITLE
Android Sign-in Crash

### ISSUE THREAD

**Issue by montzkie18** [faizann/UnityGPGPlugin#2]
Steps to reproduce:
1. Import GPGPlugin.unitypackage into Unity.
2. Copy your application's AppId into NerdGPG.cs and click on Nerdiacs/UpdateGPGFiles.
3. Attach the GPGGui.cs on a gameObject on scene, hit save then "Build and Run" for Android platform.
4. After the game runs, click on "SignIn".
5. Game will instantly close with the following logs:

```
D/NerdUnityPlayerActivity(12833): !! NerdUnityPlayerActivity:: onCreate called!
D/NerdGPG(12833): ParentActivity name is com.nerdiacs.nerdgpgplugin.NerdUnityPlayerActivity
D/NerdGPG(12833): ParentActivity name is com.nerdiacs.nerdgpgplugin.NerdUnityPlayerActivity
D/NerdGPG(12833): Connecting GamesClient.
D/NerdGPG(12833): onConnectionFailed: result 4
D/NerdGPG(12833): resolveConnectionResult: trying to resolve result: ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{42d4f940: android.os.BinderProxy@42d4f8e0}}
D/NerdGPG(12833): result has resolution. Starting it.
D/NerdGPG(12833): Resolving intent with activity com.nerdiacs.nerdgpgplugin.NerdUnityPlayerActivity@42b32ca8
D/NerdGPG(12833): onActivityResult, req 9001 response 10004
D/NerdGPG(12833): responseCode != RESULT_OK, so not reconnecting.
D/NerdGPG(12833): giveUp: giving up on connection. Status code: 4
D/NerdUnityPlayerActivity(12833): RequestCode: 9002

java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.1.5f1
Device model : samsung SAMSUNG-SGH-I747
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9002, result=0, data=null} to activity {com.nerdiacs.nerdgpgplugin.NerdUnityPlayerActivity}: java.lang.NullPointerException
at android.app.ActivityThread.deliverResults(ActivityThread.java:3205)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3248)
at android.app.ActivityThread.access$1200(ActivityThread.java:143)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4950)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.nerdiacs.nerdgpgplugin.NerdUnityPlayerActivity.onActivityResult(NerdUnityPlayerActivity.java:30)
at android.app.Activity.dispatchActivityResult(Activity.java:5363)
at android.app.ActivityThread.deliverResults(ActivityThread1.java:3201)
```

**Comment by faizann** [comment]
Are you building on OSX or Windows?

**Comment by montzkie18** [comment]
OSX

**Comment by faizann** [comment]
Hi

There was wrong if condition in java code. I have fixed it and created new jar files. 
Reimport the project or better try it in a new project so that GPGPlugin.jar file is new one.
Confirm me here please if you get it working.

**Comment by aLDime** [comment]
I bought a plug-in Plato Evolved and not worried)) Than to spend time on these deficiencies ..
And by the way it works fine GPG Realtime Multiplayer ..

**Comment by faizann** [comment]
Cool. We made the code opensource for this very reason that people can add/fix things faster themselves.
