### ISSUE TITLE
Android without GooglePlayServices Crash 

### ISSUE THREAD

**Issue by iamIcarus** [faizann/UnityGPGPlugin#3]
Android devices that dont have GooglePlayServices creates this issue

java.lang.Error: FATAL EXCEPTION [main]
Unity version : 4.2.2f1
Device model : samsung GT-P3100
Device fingerprint: samsung/espressorfxx/espressorf:4.0.4/IMM76D/P3100XWBLH3:user/release-keys

Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.R$string
at com.google.android.gms.common.GooglePlayServicesUtil.b(Unknown Source)
at com.google.android.gms.common.GooglePlayServicesUtil.a(Unknown Source)
at com.google.android.gms.common.GooglePlayServicesUtil.getErrorDialog(Unknown Source)
at com.nerdiacs.nerdgpgplugin.NerdGPG$1.run(NerdGPG.java:149)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4514)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)

**Comment by iamIcarus** [comment]
actually i didnt put the googleplayservices.jar into the "libs" folder of Unity3d but in the "Plugins" folder
